# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raden Adhitya Ardiansyah Ramadhan
title: Energy and Data Science
email: ardiansyah.raar@gmail.com
# website: https://scholar.google.com/citations?user=FnMigTUAAAAJ&hl=en #this line was website

# Dark Mode (true/false/never)
darkmode: false
# Social links
# twitter_username: adhityaraar
github_username: adhityaraar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: adhityaraar
linkedin_username: adhityaraar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Adhit_photo.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, this is Adhit!
  A highly motivated and hard-working person with strong expertise in engineering, data science, project leader, and business.
  During his college, he was assigned many projects related to artificial intelligence implementation, published 3 international journals, and attended 7 International conferences.
  If you wish to contact me, you can reach me by email or through my social media handles.

content:
  - title: #Projects # Title for the section
    # layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: My Portfolio
        # link: https://scholar.google.com/citations?user=FnMigTUAAAAJ&hl=en
        # link: https://www.linkedin.com/in/adhityaraar/
        # link_text: Project Website
        additional_links:
          - title: Publication
            icon: fab fa-github
            url: https://scholar.google.com/citations?user=FnMigTUAAAAJ&hl=en
          - title: Renewable energy website
            icon: fab fa-github
            url: https://sites.google.com/a/kookmin.ac.kr/hjlee/people
          - title: Electric power
            icon: fab fa-github
            url: http://www.ee.ui.ac.id/epes/emat/member/raden
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Please kindly to see the project and publish paper on the link above

# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
