# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raden Adhitya Ardiansyah Ramadhan
title: Energy and Data Science
email: ardiansyah.raar@gmail.com
website: linkedin.com/in/adhityaraar

# Dark Mode (true/false/never)
darkmode: false
# Social links
# twitter_username: adhityaraar
github_username:  adhityaraar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: adhityaraar
linkedin_username: adhityaraar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Adhit_photo.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, this is Adhit!
  With background in electrical and mechanical engineering. He has strong expertise in data science, engineering, project leader, commercial and industrial designer. During his college, he was assigned many projects related to artificial intelligence implementation, published 3 international journals, and attended 7 International conferences. As an extrovert person, He is also comfortable working under the pressure of deadline with target condition and enjoy working on his initiative or team.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My Portfolio
        link: https://www.notion.so/adhityaraar/Hi-This-is-My-Portfolio-6e56630c27c34f42bb07fb8dfc975b3b
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Mostly project I created during my college and company
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to learn as I have big interest in technology enthusiast and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아이티공간 ITS Co., Ltd.
        link: itsroom.co.kr/eng
        # link_text: boringcompany.com
        sub_title: Data Science
        caption: Oct 2021 - Present
        quote: >
          As consultant machine and maintenance based in South Korea
        description: | # this will include new lines to allow paragraphs
          - Data analysis of maintenance and predictive industrial machinery
          - Developing and implementing an end-to-end machine learning system

      - layout: left
        title: PT. POCI Otomasi Cerdas Indonesia
        link: replus.co
        # link_text: boringcompany.com
        sub_title: Co-Founder and producy lead
        caption: Sept 2016 - Aug 2019
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Lead product management, commercial and industrial designer
          - Raised 690M IDR (Equivalent to 50k USD) through competitions and sponsors including DIIB UI, Ministry of Research and Technology, Astra International, DIGITARAYA, and Google Cloud.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kookmin University
        caption: 2019 - 2021
        sub_title: M.Sc. Mechanical Engineering
        quote: >
          Relevant Coursework: Data science, trend forecasting, strategic
          planning, electric power engineering
        description: | # this will include new lines to allow paragraphs
          Activities: Renewable energy research group, MIKTA United Nation
          Young leader as Indonesia delegation

        - layout: left
        title: University of Indonesia
        caption: 2015 - 2019
        sub_title: B.E. Electrical Engineering
        quote: >
          Relevant Coursework: Electrical engineering, project leader,
          entrepreneurship
        description: | # this will include new lines to allow paragraphs
          Activities: Electric Power and Energy Materials Research Group
          (EMAT), Institute of Electrical and Electronics Engineers (IEEE-UI),
          robotics team, electrical engineering student’s council (IME)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in energy and data science some of my other interests and hobbies are:
      - Drawing
      - Sculpting
      - Traveling
 
      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg)
# https://github.com/adhityaraar/adhityaraar.github.io/blob/main/images/landscape-trees.jpg
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
